# -*- coding: utf-8 -*-
"""Content for the new pages (process, facility, quality, faq, privacy) + extra UI strings.
Order of language values: tr, en, fr, ar, ru. Only facts already published on the old site are used."""
L = ["tr", "en", "fr", "ar", "ru"]


def ml(*v):
    return dict(zip(L, v))


EXTRA_STRINGS = {
    "f_market": ml("Hedef Pazar", "Target Market", "Marché cible", "السوق المستهدف", "Целевой рынок"),
    "f_market_ph": ml("Örn: Körfez, Avrupa, Afrika", "e.g. Gulf, Europe, Africa", "Ex. : Golfe, Europe, Afrique", "مثال: الخليج، أوروبا، أفريقيا", "Напр.: Залив, Европа, Африка"),
    "f_qty": ml("Tahmini Adet", "Estimated Quantity", "Quantité estimée", "الكمية التقديرية", "Ориентировочный тираж"),
    "f_qty_ph": ml("Örn: 10.000 adet", "e.g. 10,000 units", "Ex. : 10 000 unités", "مثال: 10,000 قطعة", "Напр.: 10 000 шт."),
    "f_consent": ml("<a href=\"privacy.html\" target=\"_blank\" rel=\"noopener\">Aydınlatma metnini</a> okudum; bilgilerimin talebime dönüş için işlenmesini kabul ediyorum.",
                    "I have read the <a href=\"privacy.html\" target=\"_blank\" rel=\"noopener\">privacy notice</a> and agree to my details being processed to respond to my request.",
                    "J'ai lu la <a href=\"privacy.html\" target=\"_blank\" rel=\"noopener\">notice de confidentialité</a> et j'accepte le traitement de mes données pour répondre à ma demande.",
                    "قرأت <a href=\"privacy.html\" target=\"_blank\" rel=\"noopener\">إشعار الخصوصية</a> وأوافق على معالجة بياناتي للرد على طلبي.",
                    "Я прочитал(а) <a href=\"privacy.html\" target=\"_blank\" rel=\"noopener\">уведомление о конфиденциальности</a> и согласен(на) на обработку данных для ответа на запрос."),
    "f_consent_err": ml("Devam etmek için onay gerekli.", "Your consent is required to continue.", "Votre accord est nécessaire pour continuer.", "الموافقة مطلوبة للمتابعة.", "Для продолжения требуется согласие."),
    "f_fail": ml("Gönderilemedi. Lütfen tekrar deneyin ya da info@uzmancosmetic.com adresine yazın.",
                 "Could not be sent. Please try again or write to info@uzmancosmetic.com.",
                 "Envoi impossible. Réessayez ou écrivez à info@uzmancosmetic.com.",
                 "تعذّر الإرسال. حاول مجدداً أو راسلنا على info@uzmancosmetic.com.",
                 "Не удалось отправить. Повторите попытку или напишите на info@uzmancosmetic.com."),
    "foot_legal": ml("Kurumsal", "Company", "Entreprise", "الشركة", "Компания"),
    "wa_label": ml("WhatsApp ile yazın", "Chat on WhatsApp", "Écrire sur WhatsApp", "راسلنا عبر واتساب", "Написать в WhatsApp"),
    "docs_empty": ml("Güncel belge ve sertifikalarımız için bizimle iletişime geçin.", "Please contact us for our current documents and certificates.",
                     "Contactez-nous pour obtenir nos documents et certificats à jour.", "تواصل معنا للحصول على أحدث وثائقنا وشهاداتنا.",
                     "Свяжитесь с нами, чтобы получить актуальные документы и сертификаты."),
    "download": ml("İndir", "Download", "Télécharger", "تحميل", "Скачать"),
}

PAGES = {}

PAGES["process"] = dict(
    sort=30, in_nav=1, in_footer=1,
    title=ml("Süreç", "Our Process", "Notre processus", "مراحل العمل", "Процесс работы"),
    meta=ml("Brief'ten sevkiyata private label üretim süreci: koku ve formül, numune, ambalaj, üretim, kalite kontrol ve ihracat.",
            "The private label process from brief to shipment: fragrance and formula, samples, packaging, production, quality control and export.",
            "Le processus marque blanche du brief à l'expédition : parfum et formule, échantillons, packaging, production, contrôle qualité et export.",
            "مراحل التصنيع للعلامات الخاصة من الطلب حتى الشحن: العطر والتركيبة والعينات والتغليف والإنتاج ومراقبة الجودة والتصدير.",
            "Процесс производства под частной маркой от брифа до отгрузки: аромат и формула, образцы, упаковка, производство, контроль качества и экспорт."),
    h1=ml("Fikirden raflara, <em>yedi adımda</em>.", "From idea to shelf, <em>in seven steps</em>.", "De l'idée au rayon, <em>en sept étapes</em>.", "من الفكرة إلى الرف، <em>في سبع خطوات</em>.", "От идеи до полки — <em>за семь шагов</em>."),
    lead=ml("Her proje bir brief ile başlar. Aşağıdaki akış, markanızın ürününün nasıl şekillendiğini ve her aşamada sizden ne beklediğimizi gösterir.",
            "Every project starts with a brief. The flow below shows how your product takes shape and what we need from you at each stage.",
            "Chaque projet commence par un brief. Le déroulé ci-dessous montre comment votre produit prend forme et ce que nous attendons de vous à chaque étape.",
            "يبدأ كل مشروع بطلب واضح. يوضح المسار أدناه كيف يتشكّل منتج علامتك وما نحتاجه منك في كل مرحلة.",
            "Каждый проект начинается с брифа. Схема ниже показывает, как формируется продукт вашего бренда и что нам нужно от вас на каждом этапе."),
    cta=1,
    blocks=[
        dict(type="steps", title=ml("", "", "", "", ""), lead=ml("", "", "", "", ""), items=[
            dict(title=ml("Brief ve planlama", "Brief and planning", "Brief et planification", "الطلب والتخطيط", "Бриф и планирование"),
                 text=ml("Markanızı, hedef pazarınızı, ürün tipini ve tahmini adetleri birlikte netleştiririz. Pazara göre etiket ve mevzuat ihtiyaçlarını bu aşamada belirleriz.",
                         "We define your brand, target market, product type and estimated quantities together. Label and regulatory needs for the market are set at this stage.",
                         "Nous définissons ensemble votre marque, votre marché cible, le type de produit et les quantités estimées. Les besoins d'étiquetage et de réglementation sont fixés dès cette étape.",
                         "نحدد معاً علامتك وسوقك المستهدف ونوع المنتج والكميات التقديرية، ونحدد في هذه المرحلة متطلبات الملصقات واللوائح حسب السوق.",
                         "Мы вместе определяем бренд, целевой рынок, тип продукта и ориентировочные тиражи. Требования к маркировке и регулированию для рынка уточняются на этом этапе.")),
            dict(title=ml("Koku ve formül", "Fragrance and formula", "Parfum et formule", "العطر والتركيبة", "Аромат и формула"),
                 text=ml("Ar-Ge ekibimizle ürününüzün koku ve formül yönünü belirleriz; ürün grubuna göre seçenekleri birlikte değerlendiririz.",
                         "With our R&amp;D team we define the fragrance and formula direction of your product and review the options for your product group together.",
                         "Avec notre équipe R&amp;D, nous définissons l'orientation du parfum et de la formule et étudions ensemble les options pour votre gamme.",
                         "نحدد مع فريق البحث والتطوير توجّه العطر والتركيبة، ونراجع معاً الخيارات المناسبة لفئة منتجك.",
                         "Вместе с командой R&amp;D мы определяем направление аромата и формулы и обсуждаем варианты для вашей продуктовой группы.")),
            dict(title=ml("Numune ve onay", "Sample and approval", "Échantillon et validation", "العينة والاعتماد", "Образец и утверждение"),
                 text=ml("Numune hazırlanır ve size iletilir. Onayınız olmadan üretime geçilmez.",
                         "A sample is prepared and sent to you. Production does not start without your approval.",
                         "Un échantillon est préparé et vous est envoyé. La production ne démarre pas sans votre validation.",
                         "يُحضَّر نموذج ويُرسل إليك، ولا يبدأ الإنتاج قبل موافقتك.",
                         "Образец готовится и отправляется вам. Производство не начинается без вашего утверждения.")),
            dict(title=ml("Ambalaj ve baskı", "Packaging and printing", "Packaging et impression", "التغليف والطباعة", "Упаковка и печать"),
                 text=ml("50'den fazla alüminyum tüp modeli arasından formu seçersiniz; renk, kapak ve logo baskısını belirleriz. Tasarım ve grafik ekibimiz dosya hazırlığında destek olur.",
                         "You choose a form from over 50 aluminium tube models; we set colour, cap and logo printing. Our design and graphics team supports artwork preparation.",
                         "Vous choisissez une forme parmi plus de 50 modèles de tubes en aluminium ; nous définissons couleur, bouchon et impression du logo. Notre équipe design et graphisme vous aide pour les fichiers.",
                         "تختار الشكل من بين أكثر من 50 موديل من الأنابيب المعدنية، ونحدد اللون والغطاء وطباعة الشعار. ويدعمك فريق التصميم والغرافيك في تجهيز الملفات.",
                         "Вы выбираете форму из более чем 50 моделей алюминиевых туб; мы определяем цвет, колпачок и печать логотипа. Команда дизайна и графики помогает с подготовкой макетов.")),
            dict(title=ml("Üretim ve dolum", "Production and filling", "Production et remplissage", "الإنتاج والتعبئة", "Производство и розлив"),
                 text=ml("Onaylı numuneye uygun olarak aerosol ve diğer hatlarda üretim ve dolum yapılır; paketleme tamamlanır.",
                         "Production and filling take place on the aerosol and other lines in line with the approved sample, followed by packing.",
                         "La production et le remplissage sont réalisés sur les lignes aérosol et autres conformément à l'échantillon validé, puis le conditionnement.",
                         "يتم الإنتاج والتعبئة على خطوط الأيروسول وغيرها وفق العينة المعتمدة، ثم التغليف.",
                         "Производство и розлив выполняются на аэрозольных и других линиях в соответствии с утверждённым образцом, затем упаковка.")),
            dict(title=ml("Kalite kontrol", "Quality control", "Contrôle qualité", "مراقبة الجودة", "Контроль качества"),
                 text=ml("Ürünler, sevkiyattan önce onaylı numuneye ve belirlenen özelliklere göre kontrol edilir.",
                         "Products are checked against the approved sample and agreed specifications before shipment.",
                         "Les produits sont contrôlés par rapport à l'échantillon validé et aux spécifications convenues avant l'expédition.",
                         "تُفحص المنتجات قبل الشحن وفق العينة المعتمدة والمواصفات المتفق عليها.",
                         "Перед отгрузкой продукция проверяется на соответствие утверждённому образцу и согласованным спецификациям.")),
            dict(title=ml("Sevkiyat ve ihracat", "Shipping and export", "Expédition et export", "الشحن والتصدير", "Отгрузка и экспорт"),
                 text=ml("Paletleme, ihracat evrakları ve nakliye koordinasyonu için yanınızdayız; 80 ülkeye ihracat deneyimiyle.",
                         "We support palletising, export documents and freight coordination, backed by experience exporting to 80 countries.",
                         "Nous vous accompagnons pour la palettisation, les documents d'export et la coordination du transport, forts de notre expérience d'export dans 80 pays.",
                         "نرافقك في التشبيك على المنصات ووثائق التصدير وتنسيق الشحن، بخبرة تصدير إلى 80 دولة.",
                         "Мы поможем с паллетированием, экспортными документами и координацией перевозки — опираясь на опыт экспорта в 80 стран.")),
        ]),
    ],
)

PAGES["facility"] = dict(
    sort=40, in_nav=0, in_footer=2,
    title=ml("Tesis ve Kapasite", "Facility and Capacity", "Site et capacité", "المصنع والطاقة الإنتاجية", "Производство и мощности"),
    meta=ml("Çayırova / Kocaeli'deki Uzman Kozmetik tesisi: 60 milyon adet aerosol kapasitesi, Ar-Ge, tasarım ve grafik departmanları.",
            "Uzman Cosmetic's facility in Çayırova / Kocaeli: 60 million aerosol units capacity, R&D, design and graphics departments.",
            "Le site d'Uzman Cosmetic à Çayırova / Kocaeli : capacité de 60 millions d'aérosols, départements R&D, design et graphisme.",
            "مصنع أوزمان كوزمتيك في تشايروفا / قوجه إيلي: طاقة 60 مليون عبوة أيروسول وأقسام البحث والتطوير والتصميم والغرافيك.",
            "Предприятие Uzman Cosmetic в Чайырова / Коджаэли: мощность 60 млн аэрозолей, отделы R&D, дизайна и графики."),
    h1=ml("Üretimin <em>merkezi</em>.", "The <em>heart</em> of production.", "Le <em>cœur</em> de la production.", "<em>قلب</em> الإنتاج.", "<em>Сердце</em> производства."),
    lead=ml("Çayırova / Kocaeli'deki tesisimizde aerosol dolum, paketleme ve ürün geliştirme aynı çatı altında yürür.",
            "At our Çayırova / Kocaeli facility, aerosol filling, packing and product development run under one roof.",
            "Sur notre site de Çayırova / Kocaeli, le remplissage aérosol, le conditionnement et le développement produit se font sous un même toit.",
            "في منشأتنا بتشايروفا / قوجه إيلي تتم تعبئة الأيروسول والتغليف وتطوير المنتجات تحت سقف واحد.",
            "На нашем предприятии в Чайырова / Коджаэли аэрозольный розлив, упаковка и разработка продуктов работают под одной крышей."),
    cta=1,
    blocks=[
        dict(type="text", band=0, title=ml("1980'den bugüne", "From 1980 to today", "De 1980 à aujourd'hui", "من 1980 حتى اليوم", "С 1980 года до сегодня"),
             body=ml("1980'de basınçlı kaplar kanununa uygun ilk yarı otomatik aerosol makinemizle küçük bir atölyede üretime başladık. Bugün Ar-Ge, tasarım ve grafik departmanlarımızla, 60 milyon adet aerosol üretim kapasitesine sahip tesisimizden 80 ülkeye ihracat yapıyoruz.",
                     "In 1980 we began production in a small workshop with our first semi-automatic aerosol machine, compliant with pressure-vessel regulations. Today, with our R&amp;D, design and graphics departments, we export to 80 countries from a facility with a capacity of 60 million aerosol units.",
                     "En 1980, nous avons démarré la production dans un petit atelier avec notre première machine aérosol semi-automatique, conforme à la réglementation sur les récipients sous pression. Aujourd'hui, avec nos départements R&amp;D, design et graphisme, nous exportons dans 80 pays depuis un site d'une capacité de 60 millions d'aérosols.",
                     "بدأنا الإنتاج عام 1980 في ورشة صغيرة بأول ماكينة أيروسول شبه آلية مطابقة لقانون الأوعية المضغوطة. واليوم، بأقسام البحث والتطوير والتصميم والغرافيك، نصدّر إلى 80 دولة من منشأة طاقتها 60 مليون عبوة أيروسول.",
                     "В 1980 году мы начали производство в небольшой мастерской на первой полуавтоматической аэрозольной машине, соответствующей нормам для сосудов под давлением. Сегодня, с отделами R&amp;D, дизайна и графики, мы экспортируем в 80 стран с предприятия мощностью 60 млн аэрозолей.")),
        dict(type="cards", title=ml("Tek çatı altında", "Under one roof", "Sous un même toit", "تحت سقف واحد", "Под одной крышей"), items=[
            dict(title=ml("Aerosol dolum", "Aerosol filling", "Remplissage aérosol", "تعبئة الأيروسول", "Аэрозольный розлив"),
                 text=ml("Deodorant, vücut spreyi, oda spreyi ve saç spreyi gibi aerosol ürünlerde dolum hattı.", "Filling lines for aerosol products such as deodorant, body spray, room spray and hair spray.", "Lignes de remplissage pour les aérosols : déodorant, spray corporel, spray d'ambiance et laque.", "خطوط تعبئة لمنتجات الأيروسول مثل مزيل العرق وبخاخ الجسم ومعطر الجو وبخاخ الشعر.", "Линии розлива аэрозольной продукции: дезодорант, спрей для тела, освежитель воздуха и лак для волос.")),
            dict(title=ml("Ar-Ge", "R&amp;D", "R&amp;D", "البحث والتطوير", "R&amp;D"),
                 text=ml("Formül ve koku geliştirme, numune çalışmaları.", "Formula and fragrance development, sample work.", "Développement de formules et de parfums, travail sur les échantillons.", "تطوير التركيبات والعطور وأعمال العينات.", "Разработка формул и ароматов, работа с образцами.")),
            dict(title=ml("Tasarım ve grafik", "Design and graphics", "Design et graphisme", "التصميم والغرافيك", "Дизайн и графика"),
                 text=ml("Ambalaj, etiket ve baskı dosyalarının hazırlanması.", "Preparation of packaging, label and print artwork.", "Préparation des fichiers de packaging, d'étiquettes et d'impression.", "تجهيز ملفات التغليف والملصقات والطباعة.", "Подготовка макетов упаковки, этикеток и печати.")),
        ]),
    ],
)

PAGES["quality"] = dict(
    sort=50, in_nav=0, in_footer=2,
    title=ml("Kalite ve Belgeler", "Quality and Certificates", "Qualité et certificats", "الجودة والشهادات", "Качество и сертификаты"),
    meta=ml("Uzman Kozmetik'te kalite anlayışı, belgeler ve sertifikalar.", "Quality approach, documents and certificates at Uzman Cosmetic.",
            "Approche qualité, documents et certificats chez Uzman Cosmetic.", "نهج الجودة والوثائق والشهادات لدى أوزمان كوزمتيك.", "Подход к качеству, документы и сертификаты Uzman Cosmetic."),
    h1=ml("Kalite, <em>güvenin</em> temeli.", "Quality is the <em>basis</em> of trust.", "La qualité, <em>socle</em> de la confiance.", "الجودة <em>أساس</em> الثقة.", "Качество — <em>основа</em> доверия."),
    lead=ml("Uluslararası standartlara uygun teknolojiyle, müşteri ilişkilerinde güvenilirliği en önemli kriter olarak benimsiyoruz.",
            "With technology in line with international standards, we treat reliability in customer relationships as our most important criterion.",
            "Avec une technologie conforme aux normes internationales, nous faisons de la fiabilité dans la relation client notre critère le plus important.",
            "بتقنيات وفق المعايير الدولية، نعتبر الموثوقية في علاقتنا مع العملاء أهم معيار لدينا.",
            "Используя технологии, соответствующие международным стандартам, мы считаем надёжность в отношениях с клиентами главным критерием."),
    cta=1,
    blocks=[
        dict(type="text", band=0, title=ml("Yaklaşımımız", "Our approach", "Notre approche", "نهجنا", "Наш подход"),
             body=ml("1980'den bu yana basınçlı kaplar mevzuatına uygun üretim yapıyoruz. Her projede onaylı numuneyi referans alır, ürünleri sevkiyattan önce kontrol ederiz.",
                     "Since 1980 we have produced in compliance with pressure-vessel regulations. In every project we take the approved sample as the reference and check products before shipment.",
                     "Depuis 1980, nous produisons conformément à la réglementation sur les récipients sous pression. Dans chaque projet, l'échantillon validé sert de référence et les produits sont contrôlés avant expédition.",
                     "ننتج منذ عام 1980 وفق لوائح الأوعية المضغوطة. في كل مشروع نعتمد العينة المعتمدة مرجعاً ونفحص المنتجات قبل الشحن.",
                     "С 1980 года мы производим продукцию в соответствии с нормами для сосудов под давлением. В каждом проекте эталоном служит утверждённый образец, а продукция проверяется перед отгрузкой.")),
        dict(type="certs", title=ml("Belgeler ve sertifikalar", "Documents and certificates", "Documents et certificats", "الوثائق والشهادات", "Документы и сертификаты")),
    ],
)

PAGES["faq"] = dict(
    sort=60, in_nav=0, in_footer=2,
    title=ml("Sıkça Sorulan Sorular", "FAQ", "FAQ", "الأسئلة الشائعة", "Вопросы и ответы"),
    meta=ml("Private label üretim, numune, ambalaj ve ihracat hakkında sık sorulan sorular.", "Frequently asked questions about private label production, samples, packaging and export.",
            "Questions fréquentes sur la production en marque blanche, les échantillons, le packaging et l'export.", "أسئلة شائعة حول التصنيع للعلامات الخاصة والعينات والتغليف والتصدير.", "Частые вопросы о производстве под частной маркой, образцах, упаковке и экспорте."),
    h1=ml("Merak <em>edilenler</em>.", "Good <em>questions</em>.", "Vos <em>questions</em>.", "<em>أسئلتكم</em>.", "Ваши <em>вопросы</em>."),
    lead=ml("Projenize başlamadan önce en sık sorulan soruların yanıtları.", "Answers to the questions we hear most before a project starts.",
            "Les réponses aux questions les plus fréquentes avant le lancement d'un projet.", "إجابات عن الأسئلة الأكثر شيوعاً قبل بدء المشروع.", "Ответы на самые частые вопросы перед стартом проекта."),
    cta=1,
    blocks=[
        dict(type="faq", title=ml("", "", "", "", ""), items=[
            dict(q=ml("Private label üretim nasıl işler?", "How does private label production work?", "Comment fonctionne la production en marque blanche ?", "كيف يعمل التصنيع للعلامات الخاصة؟", "Как устроено производство под частной маркой?"),
                 a=ml("Siz markanızı ve ürün fikrinizi paylaşırsınız; biz formül, ambalaj, baskı ve üretimi yürütürüz. Adımları Süreç sayfasında görebilirsiniz.",
                      "You share your brand and product idea; we handle formula, packaging, printing and production. You can see the steps on the Process page.",
                      "Vous nous confiez votre marque et votre idée de produit ; nous gérons formule, packaging, impression et production. Les étapes sont détaillées sur la page Processus.",
                      "تشاركنا علامتك وفكرة المنتج ونتولى نحن التركيبة والتغليف والطباعة والإنتاج. يمكنك الاطلاع على الخطوات في صفحة مراحل العمل.",
                      "Вы делитесь брендом и идеей продукта, а мы берём на себя формулу, упаковку, печать и производство. Этапы описаны на странице «Процесс».")),
            dict(q=ml("Hangi ürün gruplarında üretim yapıyorsunuz?", "Which product groups do you manufacture?", "Quelles gammes fabriquez-vous ?", "ما فئات المنتجات التي تصنّعونها؟", "Какие группы продукции вы производите?"),
                 a=ml("Body care: deodorant, roll-on, saç ürünleri, EDP parfüm ve vücut spreyi. Home care: bambu difüzör, oda ve ortam spreyi, çubuklu difüzör.",
                      "Body care: deodorant, roll-on, hair products, EDP perfume and body mist. Home care: bamboo diffuser, room and air freshener, reed diffuser.",
                      "Soin du corps : déodorant, roll-on, produits capillaires, parfum EDP et brume corporelle. Maison : diffuseur bambou, spray d'ambiance, diffuseur à bâtonnets.",
                      "العناية بالجسم: مزيل العرق، رول أون، منتجات الشعر، عطر EDP وبخاخ الجسم. العناية بالمنزل: موزّع الخيزران، معطرات الجو والغرف، موزّع القصب.",
                      "Уход за телом: дезодорант, роллон, средства для волос, парфюм EDP и мист для тела. Для дома: бамбуковый диффузор, освежители воздуха, диффузор с палочками.")),
            dict(q=ml("Logomu ürüne bastırabilir miyim?", "Can my logo be printed on the product?", "Mon logo peut-il être imprimé sur le produit ?", "هل يمكن طباعة شعاري على المنتج؟", "Можно ли напечатать мой логотип на продукте?"),
                 a=ml("Evet. Alüminyum tüp modellerinde renk, kapak ve logo baskısını markanıza göre belirleriz; tasarım ekibimiz dosya hazırlığında destek olur.",
                      "Yes. On our aluminium tube models we set colour, cap and logo printing to match your brand, and our design team helps with artwork.",
                      "Oui. Sur nos modèles de tubes en aluminium, couleur, bouchon et impression du logo sont définis selon votre marque ; notre équipe design vous aide pour les fichiers.",
                      "نعم. في موديلات الأنابيب المعدنية نحدد اللون والغطاء وطباعة الشعار وفق علامتك، ويساعدك فريق التصميم في تجهيز الملفات.",
                      "Да. На моделях алюминиевых туб цвет, колпачок и печать логотипа подбираются под ваш бренд, а дизайн-команда помогает с макетами.")),
            dict(q=ml("Numune alabilir miyim?", "Can I get a sample?", "Puis-je obtenir un échantillon ?", "هل يمكنني الحصول على عينة؟", "Можно ли получить образец?"),
                 a=ml("Evet. Numune hazırlanır ve onayınız alınmadan üretime geçilmez. Talebinizi iletişim sayfasındaki formdan gönderebilirsiniz.",
                      "Yes. A sample is prepared and production never starts without your approval. Send your request through the form on the contact page.",
                      "Oui. Un échantillon est préparé et la production ne démarre jamais sans votre validation. Envoyez votre demande via le formulaire de la page contact.",
                      "نعم. يُحضَّر نموذج ولا يبدأ الإنتاج دون موافقتك. أرسل طلبك عبر النموذج في صفحة اتصل بنا.",
                      "Да. Образец готовится, а производство не начинается без вашего утверждения. Отправьте запрос через форму на странице контактов.")),
            dict(q=ml("Minimum sipariş adedi ve teslim süresi nedir?", "What are the minimum order quantity and lead time?", "Quels sont le minimum de commande et le délai ?", "ما الحد الأدنى للطلب ومدة التسليم؟", "Каков минимальный заказ и срок поставки?"),
                 a=ml("Ürün tipine, ambalaja ve baskıya göre değişir. Projenizi paylaşın, net bir plan ve teklif hazırlayalım.",
                      "They depend on the product type, packaging and printing. Share your project and we will prepare a clear plan and quote.",
                      "Ils dépendent du type de produit, du packaging et de l'impression. Partagez votre projet et nous préparerons un plan et un devis précis.",
                      "تختلف حسب نوع المنتج والتغليف والطباعة. شاركنا مشروعك لنعدّ لك خطة وعرض سعر واضحين.",
                      "Зависят от типа продукта, упаковки и печати. Расскажите о проекте, и мы подготовим чёткий план и коммерческое предложение.")),
            dict(q=ml("Hangi ülkelere ihracat yapıyorsunuz?", "Which countries do you export to?", "Vers quels pays exportez-vous ?", "إلى أي دول تصدّرون؟", "В какие страны вы экспортируете?"),
                 a=ml("80 ülkeye ihracat yapıyoruz. Paletleme, ihracat evrakları ve nakliye koordinasyonunda destek veriyoruz.",
                      "We export to 80 countries and support palletising, export documents and freight coordination.",
                      "Nous exportons dans 80 pays et vous accompagnons pour la palettisation, les documents d'export et la coordination du transport.",
                      "نصدّر إلى 80 دولة وندعمك في التشبيك والوثائق وتنسيق الشحن.",
                      "Мы экспортируем в 80 стран и помогаем с паллетированием, экспортными документами и координацией перевозки.")),
        ]),
    ],
)

PAGES["privacy"] = dict(
    sort=70, in_nav=0, in_footer=2,
    title=ml("Gizlilik ve KVKK", "Privacy Notice", "Confidentialité", "إشعار الخصوصية", "Конфиденциальность"),
    meta=ml("Kişisel verilerin korunması aydınlatma metni.", "Privacy notice on the processing of personal data.", "Notice d'information sur le traitement des données personnelles.", "إشعار حول معالجة البيانات الشخصية.", "Уведомление об обработке персональных данных."),
    h1=ml("Gizlilik ve <em>kişisel veriler</em>.", "Privacy and <em>personal data</em>.", "Confidentialité et <em>données personnelles</em>.", "الخصوصية و<em>البيانات الشخصية</em>.", "Конфиденциальность и <em>персональные данные</em>."),
    lead=ml("Bu metin, iletişim ve teklif formları aracılığıyla paylaştığınız bilgilerin nasıl işlendiğini açıklar.", "This notice explains how the details you share through our contact and quote forms are processed.",
            "Cette notice explique comment les informations transmises via nos formulaires de contact et de devis sont traitées.", "يوضح هذا الإشعار كيفية معالجة المعلومات التي تشاركها عبر نماذج الاتصال وطلب العروض.", "В этом уведомлении объясняется, как обрабатываются данные, которые вы передаёте через формы контактов и запроса предложения."),
    cta=0,
    blocks=[
        dict(type="text", band=0, title=ml("Veri sorumlusu", "Data controller", "Responsable du traitement", "المسؤول عن البيانات", "Оператор данных"),
             body=ml("Uzman Kozmetik Kimya San. ve Dış Tic. Ltd. Şti. — Şekerpınar Mh. Özbek Sk. No:4, Çayırova / Kocaeli. E-posta: info@uzmancosmetic.com",
                     "Uzman Kozmetik Kimya San. ve Dış Tic. Ltd. Şti. — Şekerpınar Mh. Özbek Sk. No:4, Çayırova / Kocaeli, Türkiye. Email: info@uzmancosmetic.com",
                     "Uzman Kozmetik Kimya San. ve Dış Tic. Ltd. Şti. — Şekerpınar Mh. Özbek Sk. No:4, Çayırova / Kocaeli, Turquie. E-mail : info@uzmancosmetic.com",
                     "Uzman Kozmetik Kimya San. ve Dış Tic. Ltd. Şti. — Şekerpınar Mh. Özbek Sk. No:4، تشايروفا / قوجه إيلي، تركيا. البريد: info@uzmancosmetic.com",
                     "Uzman Kozmetik Kimya San. ve Dış Tic. Ltd. Şti. — Şekerpınar Mh. Özbek Sk. No:4, Чайырова / Коджаэли, Турция. E-mail: info@uzmancosmetic.com")),
        dict(type="text", band=0, title=ml("İşlenen veriler ve amaç", "Data processed and purpose", "Données traitées et finalité", "البيانات المعالجة والغرض", "Обрабатываемые данные и цель"),
             body=ml("Formlarda paylaştığınız ad soyad, firma, e-posta, telefon ve proje bilgileri yalnızca talebinize yanıt vermek, teklif ve numune sürecini yürütmek amacıyla işlenir. Bilgileriniz yurt içinde ve yurt dışında bulunan iş ortaklarına satış amacıyla aktarılmaz.",
                     "The name, company, email, phone and project details you share in our forms are processed only to respond to your request and to run the quote and sample process. Your details are not sold or passed on to third parties for marketing.",
                     "Le nom, la société, l'e-mail, le téléphone et les informations de projet saisis dans nos formulaires ne sont traités que pour répondre à votre demande et gérer le devis et les échantillons. Vos données ne sont ni vendues ni transmises à des tiers à des fins commerciales.",
                     "تُعالج بيانات الاسم والشركة والبريد والهاتف وتفاصيل المشروع التي تشاركها في النماذج فقط للرد على طلبك وإدارة عرض السعر والعينات. لا تُباع بياناتك ولا تُنقل لأطراف ثالثة لأغراض تسويقية.",
                     "Имя, компания, e-mail, телефон и сведения о проекте, указанные в формах, обрабатываются только для ответа на запрос и ведения процесса расчёта и образцов. Ваши данные не продаются и не передаются третьим лицам в маркетинговых целях.")),
        dict(type="text", band=0, title=ml("Saklama süresi ve haklarınız", "Retention and your rights", "Conservation et vos droits", "مدة الاحتفاظ وحقوقك", "Срок хранения и ваши права"),
             body=ml("Bilgileriniz, talebinizin gerektirdiği süre boyunca saklanır. 6698 sayılı KVKK'nın 11. maddesi kapsamında bilgilerinize erişme, düzeltme veya silme talebinde bulunabilirsiniz; bunun için info@uzmancosmetic.com adresine yazmanız yeterlidir.",
                     "Your details are kept for as long as your request requires. Under Article 11 of Turkish Law No. 6698 (KVKK) you may request access, correction or deletion by writing to info@uzmancosmetic.com.",
                     "Vos données sont conservées aussi longtemps que votre demande l'exige. En vertu de l'article 11 de la loi turque n° 6698 (KVKK), vous pouvez demander l'accès, la rectification ou la suppression en écrivant à info@uzmancosmetic.com.",
                     "تُحفظ بياناتك للمدة التي يتطلبها طلبك. وبموجب المادة 11 من القانون التركي رقم 6698 (KVKK) يمكنك طلب الاطلاع أو التصحيح أو الحذف بمراسلة info@uzmancosmetic.com.",
                     "Ваши данные хранятся столько, сколько требует запрос. В соответствии со статьёй 11 закона Турции № 6698 (KVKK) вы можете запросить доступ, исправление или удаление, написав на info@uzmancosmetic.com.")),
        dict(type="text", band=0, title=ml("Çerezler", "Cookies", "Cookies", "ملفات تعريف الارتباط", "Файлы cookie"),
             body=ml("Bu site analiz veya reklam çerezi kullanmaz. Yalnızca seçtiğiniz renk temasını tarayıcınızda saklamak için yerel depolama kullanılabilir.",
                     "This site does not use analytics or advertising cookies. Local storage may be used only to remember the colour theme you choose in your browser.",
                     "Ce site n'utilise ni cookies d'analyse ni cookies publicitaires. Le stockage local peut servir uniquement à mémoriser le thème de couleur choisi dans votre navigateur.",
                     "لا يستخدم هذا الموقع ملفات تعريف ارتباط للتحليلات أو الإعلانات. قد يُستخدم التخزين المحلي فقط لحفظ سمة الألوان التي تختارها في متصفحك.",
                     "Этот сайт не использует аналитические или рекламные cookie. Локальное хранилище может использоваться только для сохранения выбранной цветовой темы в вашем браузере.")),
    ],
)
